package com.cssrc.webservice.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.cssrc.webservice.service.IDataService;
import javax.xml.ws.Service;
import cn.edu.buaa.im.service.Utility;;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-12T20:47:18.449+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "DataServiceService", 
//                  wsdlLocation = "http://202.112.140.210/MainModel/services/IDataService?wsdl",
                  targetNamespace = "http://impl.service.webservice.cssrc.com/") 
public class DataServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.webservice.cssrc.com/", "DataServiceService");
    public final static QName DataServicePort = new QName("http://impl.service.webservice.cssrc.com/", "DataServicePort");
    static {
        URL url = null;
        try {
        	url = new URL("http://202.112.140.210/MainModel/services/IDataService?wsdl");
//            url = new URL(Utility.getParameter("wsdl_url"));
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DataServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://202.112.140.210/MainModel/services/IDataService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DataServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DataServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DataServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DataServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DataServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IDataService
     */
    @WebEndpoint(name = "DataServicePort")
    public IDataService getDataServicePort() {
        return super.getPort(DataServicePort, IDataService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDataService
     */
    @WebEndpoint(name = "DataServicePort")
    public IDataService getDataServicePort(WebServiceFeature... features) {
        return super.getPort(DataServicePort, IDataService.class, features);
    }

}
