package com.cssrc.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-12T20:47:18.420+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://service.webservice.cssrc.com/", name = "IDataService")
@XmlSeeAlso({ObjectFactory.class})
public interface IDataService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNodeHistory", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.GetNodeHistory")
    @WebMethod
    @ResponseWrapper(localName = "getNodeHistoryResponse", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.GetNodeHistoryResponse")
    public java.lang.String getNodeHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "submitDataPack", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.SubmitDataPack")
    @WebMethod
    @ResponseWrapper(localName = "submitDataPackResponse", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.SubmitDataPackResponse")
    public java.lang.String submitDataPack(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "importMainModel", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.ImportMainModel")
    @WebMethod
    @ResponseWrapper(localName = "importMainModelResponse", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.ImportMainModelResponse")
    public java.lang.String importMainModel(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNodeDetail", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.GetNodeDetail")
    @WebMethod
    @ResponseWrapper(localName = "getNodeDetailResponse", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.GetNodeDetailResponse")
    public java.lang.String getNodeDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDataPackMessage", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.GetDataPackMessage")
    @WebMethod
    @ResponseWrapper(localName = "getDataPackMessageResponse", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.GetDataPackMessageResponse")
    public java.lang.String getDataPackMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validateUser", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.ValidateUser")
    @WebMethod
    @ResponseWrapper(localName = "validateUserResponse", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.ValidateUserResponse")
    public java.lang.String validateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNodeDependRelation", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.GetNodeDependRelation")
    @WebMethod
    @ResponseWrapper(localName = "getNodeDependRelationResponse", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.GetNodeDependRelationResponse")
    public java.lang.String getNodeDependRelation(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserMessage", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.GetUserMessage")
    @WebMethod
    @ResponseWrapper(localName = "getUserMessageResponse", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.GetUserMessageResponse")
    public java.lang.String getUserMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSonnodes", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.GetSonnodes")
    @WebMethod
    @ResponseWrapper(localName = "getSonnodesResponse", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.GetSonnodesResponse")
    public java.lang.String getSonnodes(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDataAreas", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.GetDataAreas")
    @WebMethod
    @ResponseWrapper(localName = "getDataAreasResponse", targetNamespace = "http://service.webservice.cssrc.com/", className = "com.cssrc.webservice.service.GetDataAreasResponse")
    public java.lang.String getDataAreas(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception_Exception;
}
