
package com.cssrc.webservice.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import com.cssrc.webservice.service.impl.DataServiceService;
//import javax.jws.WebMethod;
//import javax.jws.WebParam;
//import javax.jws.WebResult;
//import javax.jws.WebService;
//import javax.xml.bind.annotation.XmlSeeAlso;
//import javax.xml.ws.RequestWrapper;
//import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-12T20:47:18.311+08:00
 * Generated source version: 3.1.4
 * 
 */
public final class IDataService_DataServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.webservice.cssrc.com/", "DataServiceService");

    private IDataService_DataServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DataServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DataServiceService ss = new DataServiceService(wsdlURL, SERVICE_NAME);
        IDataService port = ss.getDataServicePort();  
        
        {
        System.out.println("Invoking getNodeHistory...");
        java.lang.String _getNodeHistory_arg0 = "";
        java.lang.String _getNodeHistory_arg1 = "";
        java.lang.String _getNodeHistory_arg2 = "";
        try {
            java.lang.String _getNodeHistory__return = port.getNodeHistory(_getNodeHistory_arg0, _getNodeHistory_arg1, _getNodeHistory_arg2);
            System.out.println("getNodeHistory.result=" + _getNodeHistory__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking submitDataPack...");
        java.lang.String _submitDataPack_arg0 = "";
        java.lang.String _submitDataPack_arg1 = "";
        java.lang.String _submitDataPack_arg2 = "";
        try {
            java.lang.String _submitDataPack__return = port.submitDataPack(_submitDataPack_arg0, _submitDataPack_arg1, _submitDataPack_arg2);
            System.out.println("submitDataPack.result=" + _submitDataPack__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking importMainModel...");
        java.lang.String _importMainModel_arg0 = "";
        java.lang.String _importMainModel_arg1 = "";
        try {
            java.lang.String _importMainModel__return = port.importMainModel(_importMainModel_arg0, _importMainModel_arg1);
            System.out.println("importMainModel.result=" + _importMainModel__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getNodeDetail...");
        java.lang.String _getNodeDetail_arg0 = "";
        java.lang.String _getNodeDetail_arg1 = "";
        java.lang.String _getNodeDetail_arg2 = "";
        java.lang.String _getNodeDetail_arg3 = "";
        try {
            java.lang.String _getNodeDetail__return = port.getNodeDetail(_getNodeDetail_arg0, _getNodeDetail_arg1, _getNodeDetail_arg2, _getNodeDetail_arg3);
            System.out.println("getNodeDetail.result=" + _getNodeDetail__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getDataPackMessage...");
        java.lang.String _getDataPackMessage_arg0 = "";
        java.lang.String _getDataPackMessage_arg1 = "";
        java.lang.String _getDataPackMessage_arg2 = "";
        java.lang.String _getDataPackMessage_arg3 = "";
        try {
            java.lang.String _getDataPackMessage__return = port.getDataPackMessage(_getDataPackMessage_arg0, _getDataPackMessage_arg1, _getDataPackMessage_arg2, _getDataPackMessage_arg3);
            System.out.println("getDataPackMessage.result=" + _getDataPackMessage__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking validateUser...");
        java.lang.String _validateUser_arg0 = "";
        java.lang.String _validateUser_arg1 = "";
        try {
            java.lang.String _validateUser__return = port.validateUser(_validateUser_arg0, _validateUser_arg1);
            System.out.println("validateUser.result=" + _validateUser__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getNodeDependRelation...");
        java.lang.String _getNodeDependRelation_arg0 = "";
        java.lang.String _getNodeDependRelation_arg1 = "";
        java.lang.String _getNodeDependRelation__return = port.getNodeDependRelation(_getNodeDependRelation_arg0, _getNodeDependRelation_arg1);
        System.out.println("getNodeDependRelation.result=" + _getNodeDependRelation__return);


        }
        {
        System.out.println("Invoking getUserMessage...");
        java.lang.String _getUserMessage_arg0 = "";
        java.lang.String _getUserMessage_arg1 = "";
        java.lang.String _getUserMessage_arg2 = "";
        try {
            java.lang.String _getUserMessage__return = port.getUserMessage(_getUserMessage_arg0, _getUserMessage_arg1, _getUserMessage_arg2);
            System.out.println("getUserMessage.result=" + _getUserMessage__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getSonnodes...");
        java.lang.String _getSonnodes_arg0 = "";
        java.lang.String _getSonnodes_arg1 = "";
        java.lang.String _getSonnodes_arg2 = "";
        java.lang.String _getSonnodes_arg3 = "";
        java.lang.String _getSonnodes_arg4 = "";
        try {
            java.lang.String _getSonnodes__return = port.getSonnodes(_getSonnodes_arg0, _getSonnodes_arg1, _getSonnodes_arg2, _getSonnodes_arg3, _getSonnodes_arg4);
            System.out.println("getSonnodes.result=" + _getSonnodes__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getDataAreas...");
        java.lang.String _getDataAreas_arg0 = "";
        java.lang.String _getDataAreas_arg1 = "";
        try {
            java.lang.String _getDataAreas__return = port.getDataAreas(_getDataAreas_arg0, _getDataAreas_arg1);
            System.out.println("getDataAreas.result=" + _getDataAreas__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
